runtime: custom
env: flex
service : toranetapiclient
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 20

readiness_check:
    app_start_timeout_sec: 7200

handlers:
- url: /.*
  script: auto
